In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_excel("text/Report.xls")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   기간        28 non-null     object
 1   자치구       28 non-null     object
 2   세대        28 non-null     object
 3   인구        28 non-null     object
 4   인구.1      28 non-null     object
 5   인구.2      28 non-null     object
 6   인구.3      28 non-null     object
 7   인구.4      28 non-null     object
 8   인구.5      28 non-null     object
 9   인구.6      28 non-null     object
 10  인구.7      28 non-null     object
 11  인구.8      28 non-null     object
 12  세대당인구     28 non-null     object
 13  65세이상고령자  28 non-null     object
dtypes: object(14)
memory usage: 3.2+ KB

In [4]:
df

,기간,자치구,세대,인구,인구.1,인구.2,인구.3,인구.4,인구.5,인구.6,인구.7,인구.8,세대당인구,65세이상고령자
0,기간,자치구,세대,합계,합계,합계,한국인,한국인,한국인,등록외국인,등록외국인,등록외국인,세대당인구,65세이상고령자
1,기간,자치구,세대,계,남자,여자,계,남자,여자,계,남자,여자,세대당인구,65세이상고령자
2,2019.1/4,합계,4290922,10054979,4909387,5145592,9770216,4772134,4998082,284763,137253,147510,2.28,1436125
3,2019.1/4,종로구,73914,162913,78963,83950,152778,74536,78242,10135,4427,5708,2.07,26981
4,2019.1/4,중구,61800,135836,66720,69116,125942,61992,63950,9894,4728,5166,2.04,22421
5,2019.1/4,용산구,109413,245139,119597,125542,229168,110626,118542,15971,8971,7000,2.09,38049
6,2019.1/4,성동구,137247,314608,154011,160597,306404,150287,156117,8204,3724,4480,2.23,43076
7,2019.1/4,광진구,163460,370658,179162,191496,354873,172361,182512,15785,6801,8984,2.17,46288
8,2019.1/4,동대문구,162228,363262,179100,184162,346750,172784,173966,16512,6316,10196,2.14,57570
9,2019.1/4,중랑구,181182,407211,201808,205403,402203,199730,202473,5008,2078,2930,2.22,62789
10,2019.1/4,성북구,188670,450021,217400,232621,438245,212830,225415,11776,4570,7206,2.32,68612
11,2019.1/4,강북구,143663,321151,156525,164626,317386,155075,162311,3765,1450,2315,2.21,58858
12,2019.1/4,도봉구,138175,340089,166218,173871,337820,165314,172506,2269,904,1365,2.44,56742
13,2019.1/4,노원구,217748,545486,264460,281026,541174,262593,278581,4312,1867,2445,2.49,78170
14,2019.1/4,은평구,206527,488713,235925,252788,484274,234064,250210,4439,1861,2578,2.34,78406
15,2019.1/4,서대문구,139811,324604,154410,170194,311771,150103,161668,12833,4307,8526,2.23,51085
16,2019.1/4,마포구,173517,386571,182249,204322,375106,177872,197234,11465,4377,7088,2.16,51293
17,2019.1/4,양천구,176680,466622,229486,237136,462599,227678,234921,4023,1808,2215,2.62,58930
18,2019.1/4,강서구,260152,602886,292646,310240,596287,289454,306833,6599,3192,3407,2.29,80903
19,2019.1/4,구로구,173585,438889,220013,218876,404726,200367,204359,34163,19646,14517,2.33,63017
20,2019.1/4,금천구,108823,254244,130503,123741,233981,118913,115068,20263,11590,8673,2.15,36301
21,2019.1/4,영등포구,172828,404556,203579,200977,368824,183493,185331,35732,20086,15646,2.13,56463
22,2019.1/4,동작구,179709,412031,199526,212505,398886,193622,205264,13145,5904,7241,2.22,60462
23,2019.1/4,관악구,265360,520645,260919,259726,502615,252307,250308,18030,8612,9418,1.89,73005
24,2019.1/4,서초구,172929,437007,209329,227678,432762,207206,225556,4245,2123,2122,2.5,55366
25,2019.1/4,강남구,229546,546875,262082,284793,541854,259510,282344,5021,2572,2449,2.36,68104
26,2019.1/4,송파구,276815,685361,332367,352994,678521,329046,349475,6840,3321,3519,2.45,83492
27,2019.1/4,강동구,177140,429601,212389,217212,425267,210371,214896,4334,2018,2316,2.4,59742

In [8]:
for i in df.자치구:
    print(i, end= " ")

자치구 자치구 합계 종로구 중구 용산구 성동구 광진구 동대문구 중랑구 성북구 강북구 도봉구 노원구 은평구 서대문구 마포구 양천구 강서구 구로구 금천구 영등포구 동작구 관악구 서초구 강남구 송파구 강동구

In [58]:
temp_df = df.iloc[:, [1,3,6,9,13]]
temp_df

     자치구       인구수     서울시민     외국인       고령자
0    자치구        합계      한국인   등록외국인  65세이상고령자
1    자치구         계        계       계  65세이상고령자
2     합계  10054979  9770216  284763   1436125
3    종로구    162913   152778   10135     26981
4     중구    135836   125942    9894     22421
5    용산구    245139   229168   15971     38049
6    성동구    314608   306404    8204     43076
7    광진구    370658   354873   15785     46288
8   동대문구    363262   346750   16512     57570
9    중랑구    407211   402203    5008     62789
10   성북구    450021   438245   11776     68612
11   강북구    321151   317386    3765     58858
12   도봉구    340089   337820    2269     56742
13   노원구    545486   541174    4312     78170
14   은평구    488713   484274    4439     78406
15  서대문구    324604   311771   12833     51085
16   마포구    386571   375106   11465     51293
17   양천구    466622   462599    4023     58930
18   강서구    602886   596287    6599     80903
19   구로구    438889   404726   34163     63017
20   금천구    254244   233981   20263     36301
21  영등포구    404556   368824   35732     56463
22   동작구    412031   398886   13145     60462
23   관악구    520645   502615   18030     73005
24   서초구    437007   432762    4245     55366
25   강남구    546875   541854    5021     68104
26   송파구    685361   678521    6840     83492
27   강동구    429601   425267    4334     59742

In [34]:
# temp_df.drop(1, axis=0, inplace=True)
temp_df[]

     자치구        인구     인구.3    인구.6 65세이상고령자
2     합계  10054979  9770216  284763  1436125
3    종로구    162913   152778   10135    26981
4     중구    135836   125942    9894    22421
5    용산구    245139   229168   15971    38049
6    성동구    314608   306404    8204    43076
7    광진구    370658   354873   15785    46288
8   동대문구    363262   346750   16512    57570
9    중랑구    407211   402203    5008    62789
10   성북구    450021   438245   11776    68612
11   강북구    321151   317386    3765    58858
12   도봉구    340089   337820    2269    56742
13   노원구    545486   541174    4312    78170
14   은평구    488713   484274    4439    78406
15  서대문구    324604   311771   12833    51085
16   마포구    386571   375106   11465    51293
17   양천구    466622   462599    4023    58930
18   강서구    602886   596287    6599    80903
19   구로구    438889   404726   34163    63017
20   금천구    254244   233981   20263    36301
21  영등포구    404556   368824   35732    56463
22   동작구    412031   398886   13145    60462
23   관악구    520645   502615   18030    73005
24   서초구    437007   432762    4245    55366
25   강남구    546875   541854    5021    68104
26   송파구    685361   678521    6840    83492
27   강동구    429601   425267    4334    59742

In [42]:
# temp_df['한국인비율(%)'] = (temp_df['인구.3'] / temp_df['인구']) *100
# temp_df['외국인비율(%)'] = (temp_df['인구.6'] / temp_df['인구']) *100
temp_df['고령자비율(%)'] = (temp_df['65세이상고령자'] / temp_df['인구']) *100
temp_df

<ipython-input-42-c64d70c5423e>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df['고령자비율(%)'] = (temp_df['65세이상고령자'] / temp_df['인구']) *100

     자치구        인구     인구.3    인구.6 65세이상고령자 한국인비율(%)  외국인비율(%) 고령자비율(%)
2     합계  10054979  9770216  284763  1436125  97.1679   2.83206  14.2827
3    종로구    162913   152778   10135    26981  93.7789   6.22111  16.5616
4     중구    135836   125942    9894    22421  92.7162   7.28378  16.5059
5    용산구    245139   229168   15971    38049  93.4849   6.51508  15.5214
6    성동구    314608   306404    8204    43076  97.3923   2.60769   13.692
7    광진구    370658   354873   15785    46288  95.7414   4.25864  12.4881
8   동대문구    363262   346750   16512    57570  95.4545   4.54548  15.8481
9    중랑구    407211   402203    5008    62789  98.7702   1.22983  15.4193
10   성북구    450021   438245   11776    68612  97.3832   2.61677  15.2464
11   강북구    321151   317386    3765    58858  98.8277   1.17235  18.3272
12   도봉구    340089   337820    2269    56742  99.3328  0.667178  16.6845
13   노원구    545486   541174    4312    78170  99.2095  0.790488  14.3303
14   은평구    488713   484274    4439    78406  99.0917  0.908304  16.0434
15  서대문구    324604   311771   12833    51085  96.0466   3.95343  15.7376
16   마포구    386571   375106   11465    51293  97.0342   2.96582  13.2687
17   양천구    466622   462599    4023    58930  99.1378  0.862154  12.6291
18   강서구    602886   596287    6599    80903  98.9054   1.09457  13.4193
19   구로구    438889   404726   34163    63017   92.216   7.78397  14.3583
20   금천구    254244   233981   20263    36301  92.0301    7.9699   14.278
21  영등포구    404556   368824   35732    56463  91.1676    8.8324  13.9568
22   동작구    412031   398886   13145    60462  96.8097   3.19029  14.6741
23   관악구    520645   502615   18030    73005   96.537   3.46301   14.022
24   서초구    437007   432762    4245    55366  99.0286   0.97138  12.6694
25   강남구    546875   541854    5021    68104  99.0819  0.918126  12.4533
26   송파구    685361   678521    6840    83492   99.002  0.998014  12.1822
27   강동구    429601   425267    4334    59742  98.9912   1.00884  13.9064

In [54]:
# df1.rename(columns={"인구": "인구수", "인구.3":"서울시민","인구.6":"외국인",\
#                    "65세이상고령자" :"고령자"}, inplace=True)
df1.index = df1['자치구']
df1.drop('자치구', axis=1, inplace=True)

In [57]:
df1

         인구수    서울시민    외국인    고령자 한국인비율(%)  외국인비율(%) 고령자비율(%)
자치구
종로구   162913  152778  10135  26981  93.7789   6.22111  16.5616
중구    135836  125942   9894  22421  92.7162   7.28378  16.5059
용산구   245139  229168  15971  38049  93.4849   6.51508  15.5214
성동구   314608  306404   8204  43076  97.3923   2.60769   13.692
광진구   370658  354873  15785  46288  95.7414   4.25864  12.4881
동대문구  363262  346750  16512  57570  95.4545   4.54548  15.8481
중랑구   407211  402203   5008  62789  98.7702   1.22983  15.4193
성북구   450021  438245  11776  68612  97.3832   2.61677  15.2464
강북구   321151  317386   3765  58858  98.8277   1.17235  18.3272
도봉구   340089  337820   2269  56742  99.3328  0.667178  16.6845
노원구   545486  541174   4312  78170  99.2095  0.790488  14.3303
은평구   488713  484274   4439  78406  99.0917  0.908304  16.0434
서대문구  324604  311771  12833  51085  96.0466   3.95343  15.7376
마포구   386571  375106  11465  51293  97.0342   2.96582  13.2687
양천구   466622  462599   4023  58930  99.1378  0.862154  12.6291
강서구   602886  596287   6599  80903  98.9054   1.09457  13.4193
구로구   438889  404726  34163  63017   92.216   7.78397  14.3583
금천구   254244  233981  20263  36301  92.0301    7.9699   14.278
영등포구  404556  368824  35732  56463  91.1676    8.8324  13.9568
동작구   412031  398886  13145  60462  96.8097   3.19029  14.6741
관악구   520645  502615  18030  73005   96.537   3.46301   14.022
서초구   437007  432762   4245  55366  99.0286   0.97138  12.6694
강남구   546875  541854   5021  68104  99.0819  0.918126  12.4533
송파구   685361  678521   6840  83492   99.002  0.998014  12.1822
강동구   429601  425267   4334  59742  98.9912   1.00884  13.9064

In [59]:
df1.sort_values(by="고령자비율(%)", ascending=False).head(3)

        인구수    서울시민    외국인    고령자 한국인비율(%)  외국인비율(%) 고령자비율(%)
자치구
강북구  321151  317386   3765  58858  98.8277   1.17235  18.3272
도봉구  340089  337820   2269  56742  99.3328  0.667178  16.6845
종로구  162913  152778  10135  26981  93.7789   6.22111  16.5616